#! /bin/bash

if [ "$#" -lt 1 ]; then
	echo "ERROR: PROVIDE NAME OF PROCESS"
	exit 1
elif [ "$#" -eq 1 ]; then
	processName="$1"
else
	processName="$1 "
	while [ "$#" -gt 0 ]; do
		processName+="$2 "
		shift 2
		echo $processName
	done
fi


pids=$(ps aux | grep "$processName" | grep -v grep | awk '{print $2}')

# echo "$pids"
count=0
while IFS= read -r line; do
	if [ "$count" -eq 1 ]; then
  		firstPid="$line"
  		break
	fi
	((count++))
done <<< "$pids"
kill "$firstPid"
echo "PROCESS $processName OF PID $firstPid WAS KILLED"
echo "process name $1"